spring:
  docker:
    compose:
      file: src/main/docker/compose.yml
      enabled: true
      lifecycle-management: start_only
  jpa:
    properties:
      hibernate:
        default_schema: public
  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
jwt:
  secret: o8z#b9ca-)s3r@zv#sv-fxk5q&)cdkzhqr!@2bj(6k1n84_8hcdkzhqr!@2bj(6k1n84_8h
  expiration: 86400000  # 24 hours in milliseconds